"""Add detailed fact fields

Revision ID: 761d166202d6
Revises: 748d97cad009
Create Date: 2026-01-09 20:36:05.732993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '761d166202d6'
down_revision: Union[str, Sequence[str], None] = '748d97cad009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact', sa.Column('source_text', sa.Text(), nullable=True))
    op.add_column('fact', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('fact', sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('fact', sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('fact', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact', 'metadata_')
    op.drop_column('fact', 'relationships')
    op.drop_column('fact', 'entities')
    op.drop_column('fact', 'confidence')
    op.drop_column('fact', 'source_text')
    # ### end Alembic commands ###
